pub mod action_util;
pub mod autoindent;
pub mod bracket_actions;
// Lua needs the plugin system (it talks to `plugin::pending`), so it only
// compiles when both `lua-engine` and a runtime (`plugins`) are present.
#[cfg(all(feature = "lua-engine", feature = "plugins"))]
pub mod lua;
#[cfg(feature = "plugins")]
pub mod plugin;
pub mod buffer;
pub mod colorscheme;
pub mod command;
pub mod completion;
pub mod config;
pub mod cursor;
pub mod delete_actions;
pub mod edit_actions;
pub mod editor;
pub mod event;
pub mod format_actions;
pub mod fzf;
pub mod highlight_actions;
pub mod highlights;
pub mod history;
#[cfg(feature = "render-buffer")]
pub mod image_art;
pub mod indent_actions;
pub mod jump_actions;
pub mod jumplist;
pub mod keymap;
pub mod lsp;
pub mod lsp_actions;
pub mod lsp_apply;
pub mod macros;
pub mod mode;
pub mod motion;
pub mod registers;
#[cfg(feature = "render-buffer")]
pub mod render_actions;
pub mod replace_actions;
pub mod search;
pub mod search_actions;
pub mod shell_actions;
pub mod syntax;
pub mod tab;
pub mod terminal;
pub mod text;
pub mod ui;
pub mod visual_actions;
pub mod window;
pub mod window_actions;
pub mod yank_actions;

pub use editor::Editor;
